server: un dominio cualquiera de los que se va a recuperar, sera usado para obtener la ip del servidor
host: host tal como esta en .ssh/config
ssh_private_key_password: clave de la ssh key usada en .ssh/config para el host anteriormente indicado (por alguna raz칩n no funciona y la sigue pidiendo igualmente)
user: usuario de la base de datos
passwd: contrase침a de la base de datos
remote_bind_address: ip a la que saltar si la base de datos esta en otra maquina
db_ban:
  - esquema.prefijo de las bases de datos a excluir
dom_ban:
  - dominios a excluir
url_ban:
  - dominio/url a excluir
---
server: un dominio cualquiera de los que se va a recuperar, sera usado para obtener la ip del servidor
host: host tal como esta en .ssh/config
ssh_private_key_password: clave de la ssh key usada en .ssh/config para el host anteriormente indicado (por alguna raz칩n no funciona y la sigue pidiendo igualmente)
user: usuario de la base de datos
passwd: contrase침a de la base de datos
